/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2011 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "dnGameNames.h"

// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_DNGAME_ANIM_ENUMS
#define INCLUDED_DNGAME_ANIM_ENUMS 1

enum EWeaponState
{
    DUKE_WEAPONSTATE_IDLE   =0,
    DUKE_WEAPONSTATE_FIRE   =1,
    DUKE_WEAPONSTATE_MAX    =2,
};
#define FOREACH_ENUM_EWEAPONSTATE(op) \
    op(DUKE_WEAPONSTATE_IDLE) \
    op(DUKE_WEAPONSTATE_FIRE) 

#endif // !INCLUDED_DNGAME_ANIM_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_DNGAME_ANIM_CLASSES
#define INCLUDED_DNGAME_ANIM_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

class UAnimNotify_WeaponState : public UAnimNotify
{
public:
    //## BEGIN PROPS AnimNotify_WeaponState
    MS_ALIGN(4) BYTE weaponState GCC_ALIGN(4); // Extra alignment flags needed because all properties are bytes
    SCRIPT_ALIGN;
    //## END PROPS AnimNotify_WeaponState

    DECLARE_CLASS(UAnimNotify_WeaponState,UAnimNotify,0,dnGame)
	// AnimNotify interface.
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual FString GetEditorComment() { return (FootDown == 0) ? TEXT("Left Footstep") : TEXT("Right Footstep"); }
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_DNGAME_ANIM_CLASSES
#endif // !NAMES_ONLY


#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef DNGAME_ANIM_NATIVE_DEFS
#define DNGAME_ANIM_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_DNGAME_ANIM \
	UAnimNotify_WeaponState::StaticClass(); \

#endif // DNGAME_ANIM_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(UAnimNotify_WeaponState,AnimNotify_WeaponState,weaponState)
VERIFY_CLASS_SIZE_NODIE(UAnimNotify_WeaponState)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
